//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Editable_GridView1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        [Required(ErrorMessage="Please enter name in max 250 characters")]
        [StringLength(150)]
        public string Name { get; set; }
        [Required(ErrorMessage="Please enter Age")]
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage="Please enter Departement")]
        public Nullable<int> Departement { get; set; }
        [Required(ErrorMessage="Please enter Salary in range 1000 to 10000")]
        [Range(1000,10000)]
        public Nullable<double> Salary { get; set; }
    }
}
